theme: jekyll-theme-minimal
title: Distant Reading Swiss Literature
logo: /images/img1.jpg
description: "Ernst Ludwig Kirchner (1880-1938): Rückkehr der Tiere, 1919"
url: https://www.researchgate.net/project/High-Mountains-Low-Arousal-Distant-Reading-Topographies-of-Sentiment-in-German-Swiss-Novels-in-the-early-20th-Century
